global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
receivers:
    - name: webhook_receiver
      webhook_configs:
        - url: "http://prom2teams:8089/v2/Connector"
          send_resolved: true
