global:
  scrape_interval: 10s
  # How frequently to evaluate rules
  evaluation_interval: 10s
  
  external_labels:
    monitor: 'playground-monitor'

# Rules and alerts are read from the specified file(s)
rule_files:
  - rules.yml

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /prometheus/metrics

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]
      path_prefix: /alertmanager/
